spring.datasource.url=jdbc:mysql://db-devops-sumativa.caansb7o9wbj.us-east-1.rds.amazonaws.com:3306/Sucursal?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrival=true
spring.datasource.username=admin
spring.datasource.password=db-devops-sumativa
spring.jpa.hibernate.ddl-auto=update
springdoc.api-docs.path=/api-docs
